name: x86-64-linux

on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
  workflow_dispatch:

env:
  LD_LIBRARY_PATH: ${{ github.workspace }}/build/install/lib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Test
      # run our script that builds the chops library, dependencies and unittests, runs them
      run: |
        sudo apt install -y valgrind
        sh ci/ci-x86-64-linux.sh

